### ISSUE TITLE
Errors with Create [Fabric] 0.5.1b

### ISSUE THREAD

**Issue by rinebergc** [Snownee/JadeAddonsFabric#9]
### Minecraft version

1.19.2

### Mod version

3.1.0

### Modloader version

Fabric Loader 0.14.21 + Fabric API 0.76.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Errors when loading. Game does not crash.

Testing with the following mods:
```
create-fabric-0.5.1-b-build.1060+mc1.19.2.jar
fabric-api-0.76.0+1.19.2.jar
Jade-1.19.1-fabric-8.7.3.jar
JadeAddons-1.19.2-fabric-3.1.0.jar
```

Relevant Log Excerpts:
```
[19:34:39] [main/WARN]: Error loading class: com/simibubi/create/content/contraptions/goggles/GoggleOverlayRenderer (java.lang.ClassNotFoundException: com/simibubi/create/content/contraptions/goggles/GoggleOverlayRenderer)
[19:34:39] [main/WARN]: @Mixin target com.simibubi.create.content.contraptions.goggles.GoggleOverlayRenderer was not found jadeaddons.mixins.json:create.GoggleOverlayRendererMixin from mod jadeaddons
```
```
[19:35:18] [Render thread/ERROR]: Error loading plugin at null
net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'jade' provided by 'jadeaddons'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56) ~[fabric-loader-0.14.21.jar:?]
	at snownee.jade.Jade.lambda$loadComplete$6(Jade.java:168) ~[Jade-1.19.1-fabric-8.7.3.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at snownee.jade.Jade.loadComplete(Jade.java:163) ~[Jade-1.19.1-fabric-8.7.3.jar:?]
	at snownee.jade.JadeClient.lambda$onInitializeClient$1(JadeClient.java:87) ~[Jade-1.19.1-fabric-8.7.3.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:38) ~[fabric-lifecycle-events-v1-2.2.4+1b46dc7890-db0fd3f5dc0d6099.jar:?]
	at net.minecraft.class_310.handler$zmd000$fabric-lifecycle-events-v1$onStart(class_310.java:5484) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:747) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
Caused by: net.fabricmc.loader.api.LanguageAdapterException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:60) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.21.jar:?]
	... 15 more
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:58) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.21.jar:?]
	... 15 more
Caused by: java.lang.NoClassDefFoundError: com/simibubi/create/content/logistics/trains/track/TrackTileEntity
	at snownee.jade.addon.JadeAddonsBase.lambda$static$0(JadeAddonsBase.java:27) ~[JadeAddons-1.19.2-fabric-3.1.0.jar:?]
	at snownee.jade.addon.JadeAddonsBase.lambda$new$5(JadeAddonsBase.java:37) ~[JadeAddons-1.19.2-fabric-3.1.0.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at snownee.jade.addon.JadeAddonsBase.<init>(JadeAddonsBase.java:35) ~[JadeAddons-1.19.2-fabric-3.1.0.jar:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:58) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.21.jar:?]
	... 15 more
Caused by: java.lang.ClassNotFoundException: com.simibubi.create.content.logistics.trains.track.TrackTileEntity
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at snownee.jade.addon.JadeAddonsBase.lambda$static$0(JadeAddonsBase.java:27) ~[JadeAddons-1.19.2-fabric-3.1.0.jar:?]
	at snownee.jade.addon.JadeAddonsBase.lambda$new$5(JadeAddonsBase.java:37) ~[JadeAddons-1.19.2-fabric-3.1.0.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at snownee.jade.addon.JadeAddonsBase.<init>(JadeAddonsBase.java:35) ~[JadeAddons-1.19.2-fabric-3.1.0.jar:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:58) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.21.jar:?]
	... 15 more
```

**Comment by Snownee** [comment]
It will be supported after its official release
